trigger: none

pool: Mike


stages:
  - stage: Build 
    jobs:
      - job: 
        steps:
        - task: NodeTaskRunnerInstaller@0
          inputs:
            nodeVersion: '16'
        - task: Npm@1
          inputs:
            command: 'install'
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run build'
        # - task: PublishBuildArtifacts@1
        #   inputs:
        #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        #     ArtifactName: 'drop'
        #     publishLocation: 'Container'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)'
            artifact: 'drop'
            publishLocation: 'pipeline'

  - stage: Deploye
    jobs:
      - job: 
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'drop'
              targetPath: '$(Pipeline.Workspace)'
          # - task: DownloadPipelineArtifact@2
          #   inputs:
          #     buildType: 'specific'
          #     project: '25c201eb-c555-463d-b413-50f09e1b0ac4'
          #     definition: '32'
          #     specificBuildWithTriggering: true
          #     buildVersionToDownload: 'specific'
          #     pipelineId: '406'
          #     artifactName: 'drop'
          #     targetPath: '$(Pipeline.Workspace)'
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'vmservice'
              sourceFolder: '$(Pipeline.Workspace)/build'
              contents: '**'
              targetFolder: '/home/sanjay'
              readyTimeout: '20000'
          