trigger: none

pool: B17_AgentPool


stages:
  - stage: Build 
    jobs:
      - job: 
        steps:
        - task: NodeTaskRunnerInstaller@0
          inputs:
            nodeVersion: '16'
        - task: Npm@1
          inputs:
            command: 'install'
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run build'
        # - task: PublishBuildArtifacts@1
        #   inputs:
        #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        #     ArtifactName: 'drop'
        #     publishLocation: 'Container'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)'
            artifact: 'drop'
            publishLocation: 'pipeline'

  - stage: Deploye
    jobs:
      - job: 
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'drop'
              targetPath: '$(Pipeline.Workspace)'
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'vmservice'
              sourceFolder: '($(System.DefaultWorkingDirectory)/build'
              contents: '**'
              targetFolder: '/home/sanjay'
              readyTimeout: '20000'
          