trigger: none

pool: B17_AgentPool

stages:
  - stage: Build
    jobs:
      - job: 
        steps:
          - task: NodeTaskRunnerInstaller@0
            inputs:
              nodeVersion: '6'
          - task: Npm@1
            inputs:
              command: 'install'
          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run build'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  - stage: Deploy
    jobs:
      - job: 
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)/build'
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'vmservice'
              sourceFolder: '$(System.DefaultWorkingDirectory)/build'
              contents: '**'
              targetFolder: '/home/sanjay/artifact'
              readyTimeout: '20000'
          - task: SSH@0
            inputs:
              sshEndpoint: 'vmservice'
              runOptions: 'inline'
              inline: |
                export DEBIAN_FRONTEND=noninteractive
                sudo apt-get update -y
                sudo apt-get install nginx -y
                sudo systemctl restart nginx
                sudo cp -r /home/sanjay/artifact/* /var/www/html/
              readyTimeout: '20000'