trigger: none

pool: B17_AgentPool


stages:
  - stage: Build 
    jobs:
      - job: 
        steps:
        - task: NodeTaskRunnerInstaller@0
          inputs:
            nodeVersion: '16'
        - task: Npm@1
          inputs:
            command: 'install'
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run build'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/build'
            artifact: 'drop'
            publishLocation: 'pipeline'

  - stage: Deploye
    jobs:
      - job: 
        steps:
          # - task: DownloadPipelineArtifact@2
          #   inputs:
          #     buildType: 'current'
          #     artifactName: 'drop'
          #     targetPath: '$(System.DefaultWorkingDirectory)/build'
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '25c201eb-c555-463d-b413-50f09e1b0ac4'
              definition: '32'
              buildVersionToDownload: 'specific'
              pipelineId: '421'
              artifactName: 'drop'
              targetPath: '$(System.DefaultWorkingDirectory)/sanjay'
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'vmservice'
              sourceFolder: '$(System.DefaultWorkingDirectory)/sanjay'
              contents: '**'
              targetFolder: '/home/devopsadmin/welcome'
              readyTimeout: '20000'
          - task: SSH@0
            inputs:
              sshEndpoint: 'vmservice'
              runOptions: 'inline'
              inline: |
                sudo apt update -y
                sudo apt install nginx -y
                sudo systemctl start nginx
                sudo cp -r /home/devopsadmin/welcome/* /var/www/html/
              readyTimeout: '20000'
          